
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cawfmtntijvtiemplmff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhd2ZtdG50aWp2dGllbXBsbWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDcyODQsImV4cCI6MjA1OTE4MzI4NH0.jhPoSziLG0WBQnVwBmdvVanHyccc6l0BkRyIDa17-ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
